# .github/workflows/pr-to-slack.yml
name: Notify Slack on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚀 *PR Opened* by ${{ github.actor }}:\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
