# .github/workflows/notify-slack-on-push.yml
name: Notify Slack on Push

on:
  push:  # Triggers on any push to any branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "📦 *Push Alert*\n*Branch:* ${{ github.ref_name }}\n*Pushed by:* ${{ github.actor }}\n*Commit:* <${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
